// the constants
const LIST_CSV_FILENAME = 'gists.csv';
const LIST_CSV_WITH_FILES_FILENAME = 'gists-with-files.csv';
const MY_GISTS_DIRNAME = 'my-gists';
const FORKED_GISTS_DIRNAME = 'forked-gists';
const STARRED_GISTS_DIRNAME = 'starred-gists';
const LIST_CSV_STARRED_FILENAME = 'starred-gists.csv';
const LIST_CSV_STARRED_WITH_FILES_FILENAME = 'starred-gists.csv';
const LIST_CSV_STARRED_REPOS_FILENAME = 'starred-repos.csv';

module.exports = {
  LIST_CSV_FILENAME,
  LIST_CSV_WITH_FILES_FILENAME,
  MY_GISTS_DIRNAME,
  FORKED_GISTS_DIRNAME,
  STARRED_GISTS_DIRNAME,
  LIST_CSV_STARRED_FILENAME,
  LIST_CSV_STARRED_WITH_FILES_FILENAME,
  LIST_CSV_STARRED_REPOS_FILENAME,
};
